# ============================================================================
# Figure 4D: ISR Scores by Proliferative Group
# ============================================================================
# This script compares ISR scores (Avg_Factor1) between Proliferative vs
# Non-Proliferative tissues (split at median proliferation score).
#
# Based on: Scipts_for_Figures/gtex/Check these proliferation scripts/
#           P2025_02_14_ProliferationScores_per_PlaceofDeath.R
#
# Prerequisites:
#   - Run Scripts/gtex/Tissue_proliferation_index.R to generate proliferation data
#   - Hedges G results from deathplace analysis
#
# Output:
#   - Figure_4D.png: ISR scores by proliferative group
# ============================================================================

rm(list = ls())

library(tidyverse)
library(edgeR)
library(corrr)
library(dplyr)
library(tibble)
library(ggpubr)
library(readr)
library(ggplot2)
library(ComplexHeatmap)
library(circlize)
library(beepr)
library(ggplot2)
library(ggpubr)
library(FSA)      # For Dunn's test
library(dplyr)
library(boot)
library(effsize)
library(here)

# ============================================================================
# OUTPUT DIRECTORY
# ============================================================================
Folder_name <- "Figure_4D_Proliferation_vs_ISR"
folder_path <- here("Results", "Figures", Folder_name)
if (!dir.exists(folder_path)) dir.create(folder_path, recursive = TRUE)
folder_path_1stfolder <- folder_path

shared_out_dir <- here("Results", "Figures")
if (!dir.exists(shared_out_dir)) dir.create(shared_out_dir, recursive = TRUE)

# ============================================================================
# INPUT FILES
# ============================================================================
# Proliferation scores (generated by Tissue_proliferation_index.R)
csv_prolif_of_tissues <- here("Data", "gtex", "Processed", "proliferation_index_Jack_Devine_namesChanged.csv")

if (!file.exists(csv_prolif_of_tissues)) {
  stop(paste0(
    "\n============================================================\n",
    "ERROR: Proliferation index file not found!\n\n",
    "Expected: ", csv_prolif_of_tissues, "\n\n",
    "Please run Scripts/gtex/Tissue_proliferation_index.R first.\n",
    "============================================================\n"
  ))
}
proliferation_scores <- read.csv(csv_prolif_of_tissues)

# NOTE: proliferation_score is log2-scaled from Tissue_proliferation_index.R
# (method: sum(3 raw TPMs) per sample → average raw sums across donors → log2)
# No further log2 transformation needed.

# ISR scores: build per-tissue Avg_Factor1 from per-tissue Plot_Data CSVs
# (replaces the legacy Averages_of_ISR_and_GDF15.csv, which was never written
# by any script in this repo). Filter to Hospital inpatient + Emergency room
# to match the deathplace-only averages the downstream merge expects.
source(here("Main Figure Scripts", "Helper Scripts",
            "Load_All_Tissue_DTHPLCE.R"))
all_donor_data <- load_all_tissue_dthplce() %>%
  filter(DTHPLCE %in% c("Hospital inpatient", "Emergency room"))

ISR_scores <- all_donor_data %>%
  filter(fa_vs_gdf15 == "Factor1") %>%
  group_by(Tissue) %>%
  summarise(
    Avg_Factor1 = mean(value, na.rm = TRUE),
    SD_Factor1  = sd(value,   na.rm = TRUE),
    SEM_Factor1 = SD_Factor1 / sqrt(sum(!is.na(value))),
    N_Factor1   = sum(!is.na(value)),
    .groups = "drop"
  )

# Significance results (Hedges G) — written by Figure_4C.R
csv_sig <- here("Results", "Figures", "Figure_4C", "1_Hedges_G_results.csv")
if (!file.exists(csv_sig)) {
  stop(paste0(
    "\n============================================================\n",
    "ERROR: Hedges G results not found at:\n  ", csv_sig, "\n\n",
    "Please run Figure_4C.R before Figure 4D.\n",
    "============================================================\n"
  ))
}
sig_columns <- read.csv(csv_sig)

# ============================================================================
# MERGE DATA
# ============================================================================
# Debug: Show tissue names to check for mismatches
message("\n=== Checking tissue name matching ===")
message("Tissues in ISR_scores: ", nrow(ISR_scores))
message("Tissues in proliferation_scores: ", nrow(proliferation_scores))

# Perform a left join to add the proliferation_score column to ISR_score
merged_df <- merge(ISR_scores, proliferation_scores[, c("Tissue", "proliferation_score")],
                   by = "Tissue",
                   all.x = TRUE)

# Show which tissues are missing proliferation scores
missing_prolif <- merged_df %>% filter(is.na(proliferation_score)) %>% pull(Tissue)
if (length(missing_prolif) > 0) {
  message("\nWARNING: ", length(missing_prolif), " tissues missing proliferation scores:")
  message(paste("  -", missing_prolif, collapse = "\n"))
  message("\nThese tissue names in proliferation_scores:")
  message(paste(head(proliferation_scores$Tissue, 10), collapse = ", "), "...")
}

# Split into Factor1_sig and GDF15_sig
Factor1_sig <- sig_columns %>%
  filter(Comparison == "Hospital inpatient_Factor1 vs Emergency room_Factor1") %>%
  distinct(Tissue, .keep_all = TRUE)

GDF15_sig <- sig_columns %>%
  filter(Comparison == "Hospital inpatient_GDF15 vs Emergency room_GDF15") %>%
  distinct(Tissue, .keep_all = TRUE)

# Add the Significant column from Factor1_sig to merged_df
merged_df <- merged_df %>%
  left_join(Factor1_sig %>% select(Tissue, Significant), by = "Tissue")

merged_df <- merged_df %>%
  left_join(Factor1_sig %>% select(Tissue, Cohens_D), by = "Tissue") %>%
  mutate(deathplace_comparison = ifelse(Cohens_D > 0, "HI>ER", "ER>HI"))

# Drop the Cohens_D column if not needed
merged_df <- merged_df %>% select(-Cohens_D)


# Define tissues to remove
tissues_to_remove <- c("pancreas", "kidney_cortex", "uterus", "vagina", "spleen", "small_intestines_terminal_ileum")

# Filter out the unwanted tissues
filtered_df <- merged_df %>%
  filter(!Tissue %in% tissues_to_remove)

merged_df <- filtered_df

spearman_result <- cor.test(merged_df$proliferation_score, merged_df$Avg_Factor1, method = "spearman")
spearman_rho <- spearman_result$estimate
spearman_p <- spearman_result$p.value

# Compute axis limits from data with 10% padding
x_range_p1 <- range(merged_df$proliferation_score, na.rm = TRUE)
y_range_p1 <- range(merged_df$Avg_Factor1, na.rm = TRUE)
x_pad_p1   <- diff(x_range_p1) * 0.1
y_pad_p1   <- diff(y_range_p1) * 0.1

# This is the spearman rho of the ISR score of each tissue vs the proliferation score including significant AND NON significant tissues (in terms of their HI>ER or ER>HI)
p1 <- ggplot(merged_df, aes(x = proliferation_score, y = Avg_Factor1)) +
  geom_smooth(method = "lm", color = "red", se = TRUE, alpha = 0.15) +
  geom_point(alpha = 0.7, size = 3) +
  labs(title = "prolif_score vs AvgISR Spearman All Tissues (Sig plus Non Sig)",
       x = "proliferation_score(log2)",
       y = "Avg_Factor1") +
  scale_x_continuous(limits = c(x_range_p1[1] - x_pad_p1, x_range_p1[2] + x_pad_p1), expand = c(0, 0)) +
  scale_y_continuous(limits = c(y_range_p1[1] - y_pad_p1, y_range_p1[2] + y_pad_p1), expand = c(0, 0)) +
  annotate("text", x = x_range_p1[1], y = y_range_p1[2] + y_pad_p1 * 0.5,
           label = paste0("Spearman rho: ", round(spearman_rho, 4), "\n",
                          "p-value: ", formatC(spearman_p, format = "e", digits = 2)),
           hjust = 0, vjust = 1, size = 4.5, color = "black", fontface = "italic") +
  theme_minimal() +
  theme(legend.position = "right", legend.title = element_blank())

# Display the plot
print(p1)
ggsave(filename = file.path(folder_path_1stfolder, "spearman_rho_ISRscore_vs_proliferation_both_non_and_sig.png"), plot = p1, width = 14, height = 10)


# Here we are Filtering by Significance= Significant:

data <- merged_df %>%
  select(Tissue, Avg_Factor1, proliferation_score, Significant, deathplace_comparison)

# Scale the proliferation_score column
# data <- data %>%
#   mutate(proliferation_score = scale(proliferation_score))

data_sig <- data %>%
  filter(Significant != "Not Significant")

# Calculate Spearman correlation
spearman_result <- cor.test(data_sig$proliferation_score, data_sig$Avg_Factor1, method = "spearman")
spearman_rho <- spearman_result$estimate
spearman_p <- spearman_result$p.value


# Compute axis limits from data with 10% padding
x_range_p2 <- range(data_sig$proliferation_score, na.rm = TRUE)
y_range_p2 <- range(data_sig$Avg_Factor1, na.rm = TRUE)
x_pad_p2   <- diff(x_range_p2) * 0.1
y_pad_p2   <- diff(y_range_p2) * 0.1

# Create the scatterplot with 95% confidence interval and colored points
p2 <- ggplot(data_sig, aes(x = proliferation_score, y = Avg_Factor1)) +
  geom_smooth(method = "lm", color = "red", se = TRUE, alpha = 0.15) +
  geom_point(alpha = 0.7, size = 6) +
  labs(title = "proliferation_score vs Avg_Factor1 Spearman Correlation",
       x = "proliferation_score(log2)",
       y = "Avg_Factor1") +
  scale_x_continuous(limits = c(x_range_p2[1] - x_pad_p2, x_range_p2[2] + x_pad_p2), expand = c(0, 0)) +
  scale_y_continuous(limits = c(y_range_p2[1] - y_pad_p2, y_range_p2[2] + y_pad_p2), expand = c(0, 0)) +
  annotate("text", x = x_range_p2[1], y = y_range_p2[2] + y_pad_p2 * 0.5,
           label = paste0("Spearman rho: ", round(spearman_rho, 4), "\n",
                          "p-value: ", formatC(spearman_p, format = "e", digits = 2)),
           hjust = 0, vjust = 1, size = 4.5, color = "black", fontface = "italic") +
  theme_minimal() +
  theme(legend.position = "right", legend.title = element_blank())

# Display the plot
print(p2)



#####################################################################################################################################################################
# Now we want to split the data in two separate ways :
# 1. Have a cutoff of 3 for proliferation score to generate two groupings of tissues: Proliferative vs Non-Proliferative And compare the ISR scores between these two groups
    # Need to figure out how to split these into such groups, options include:
          #                                                                   - splitting between suspected tissues switching from prolif to non prolif, such as between breast mammary tissue and thyroid (non prolif)
          #                                                                   - splitting at the median

# 2. Split the tissues into the groups from plot 2G, where some tissues have significant HI>ER and some have ER>HI. Then, compare the proliferation scores of the two groups. Get Hedges G.



# Calculate the median of the proliferation_score column
median_proliferation_score <- median(data_sig$proliferation_score, na.rm = TRUE)

# Print the result
print(median_proliferation_score)


#####
# 1 #  THIS IS FIGURE 4D
#####
data_sig <- data_sig %>%
  mutate(Proliferative_Group = ifelse(proliferation_score > median_proliferation_score, "Proliferative", "Non-Proliferative"))

# Check normality for Avg_Factor1 in both groups
normality_results <- data_sig %>%
  group_by(Proliferative_Group) %>%
  summarise(shapiro_p_value = shapiro.test(Avg_Factor1)$p.value)

# View the normality results
print(normality_results)


  # Perform Wilcoxon rank-sum test
test_result <- wilcox.test(Avg_Factor1 ~ Proliferative_Group, data = data_sig)

# View test result
print(test_result)

# Filter data for Proliferative and Non-Proliferative groups
subset_data <- data_sig %>%
  filter(Proliferative_Group %in% c("Proliferative", "Non-Proliferative"))

# # Calculate Cohen's d with Hedges' g correction
hedges_g <- cohen.d(subset_data$Avg_Factor1,
                    as.factor(subset_data$Proliferative_Group),
                    hedges.correction = TRUE)
g_value <- hedges_g$estimate

# Print the result
print(g_value)

# View the result
print(hedges_g)


# Define custom colors
custom_colors <- c("Non-Proliferative" = "blue", "Proliferative" = "purple")


# Compute y-axis limits from data with 10% padding
y_range_4D <- range(data_sig$Avg_Factor1, na.rm = TRUE)
y_pad_4D   <- diff(y_range_4D) * 0.1

# Create the plot (FIGURE 4D)
plot_4D <- ggplot(data_sig, aes(x = Proliferative_Group, y = Avg_Factor1, color = Proliferative_Group)) +
  geom_jitter(width = 0.2, size = 6, alpha = 0.7) +  # Larger jittered points
  stat_summary(fun = median, geom = "crossbar", width = 0.4,
               aes(ymin = after_stat(y), ymax = after_stat(y), color = Proliferative_Group),
               size = 0.5, alpha = 0.5) +  # More transparent median lines
  labs(title = "Comparison of Avg_Factor1 by Proliferative Group",
       x = "Proliferative Group",
       y = "Avg_Factor1") +
  scale_y_continuous(limits = c(y_range_4D[1] - y_pad_4D, y_range_4D[2] + y_pad_4D), expand = c(0, 0)) +
  scale_x_discrete(expand = expansion(add = 0.6)) +
  theme_minimal() +
  theme(legend.position = "none") +  # Remove legend
  scale_color_manual(values = custom_colors)  # Apply custom colors


# Display the plot
print(plot_4D)

ggsave(filename = file.path(folder_path_1stfolder, paste0("ISRscore_per_prolif_group_", round(median_proliferation_score, 3), "_Hedges_G_", round(g_value, 3), ".png")), plot = plot_4D, width = 14, height = 10)

# Save as Figure_4D.png to shared output folder

ggsave(filename = file.path(folder_path_1stfolder, "significant_Tissues_spearman_rho_ISRscore_vs_proliferation.png"), plot = plot_4D, width = 14, height = 10)
ggsave(filename = file.path(shared_out_dir, "Figure_4D.png"), plot = p2, width = 14, height = 10)

message("\n=== Figure 4D Complete ===")
message("Hedges G (ISR by Proliferative Group): ", round(g_value, 3))
message("Median proliferation score cutoff: ", round(median_proliferation_score, 3))
message("Saved to: ", file.path(shared_out_dir, "Figure_4D.png"))

# ============================================================================
# SAVE SOURCE DATA FOR FIGURE 4D
# ============================================================================
message("\nExporting source data for Figure 4D...")

# Prepare source data for the main figure (ISR scores by Proliferative Group)
# Include only the columns shown in the plot
source_data <- data_sig %>%
  select(Tissue, Proliferative_Group, Avg_Factor1, proliferation_score)

# Save to CSV
csv_source_file <- file.path(folder_path, "Figure_4D_source_data.csv")
write.csv(source_data, csv_source_file, row.names = FALSE)

message("  Saved: Figure_4D_source_data.csv")
message("  Location: ", folder_path)

# ============================================================================
# ADDITIONAL SOURCE DATA FOR FIGURE 4D:
# Tab 1: Summary mean Spearman rhos for ISR and Proliferation
# Tab 2: Individual tissue Spearman rho values (ISR + Proliferation)
# ============================================================================

# Tab 1: Summary — average ISR score and proliferation score across tissues
fig4d_summary <- data_sig %>%
  summarise(
    Mean_ISR_Factor1 = mean(Avg_Factor1, na.rm = TRUE),
    Mean_Proliferation_Score = mean(proliferation_score, na.rm = TRUE),
    Spearman_Rho = spearman_rho,
    Spearman_P = spearman_p,
    N_Tissues = n()
  )
write.csv(fig4d_summary,
          file.path(folder_path, "Figure_4D_summary_means.csv"),
          row.names = FALSE)
message("  Saved: Figure_4D_summary_means.csv")

# Tab 2: Individual tissue-level ISR and Proliferation scores
fig4d_individual <- data_sig %>%
  select(Tissue, Avg_Factor1, proliferation_score, Significant, deathplace_comparison, Proliferative_Group) %>%
  arrange(desc(Avg_Factor1))
write.csv(fig4d_individual,
          file.path(folder_path, "Figure_4D_individual_tissue_scores.csv"),
          row.names = FALSE)
message("  Saved: Figure_4D_individual_tissue_scores.csv (", nrow(fig4d_individual), " rows)")
