# ============================================================================
# Figure 4E: Proliferation Scores by Death Place Comparison
# ============================================================================
# This script compares proliferation scores between tissues with significant
# HI>ER vs ER>HI ISR patterns.
#
# Based on: Scipts_for_Figures/gtex/Check these proliferation scripts/
#           P2025_02_14_ProliferationScores_per_PlaceofDeath.R
#
# Prerequisites:
#   - Run Scripts/gtex/Tissue_proliferation_index.R to generate proliferation data
#   - Hedges G results from deathplace analysis
#
# Expected Output:
#   - Figure_4E.png: Proliferation scores by death place comparison
#   - Hedges G ≈ 1.17 with 14 ER>HI and 17 HI>ER tissues
# ============================================================================

rm(list = ls())

library(tidyverse)
library(edgeR)
library(corrr)
library(dplyr)
library(tibble)
library(ggpubr)
library(readr)
library(ggplot2)
library(ComplexHeatmap)
library(circlize)
library(beepr)
library(ggplot2)
library(ggpubr)
library(FSA)      # For Dunn's test
library(dplyr)
library(boot)
library(effsize)
library(here)

# ============================================================================
# OUTPUT DIRECTORY
# ============================================================================
Folder_name <- "Figure_4E_Proliferation_by_Death_Place"
folder_path <- here("Results", "Figures", Folder_name)
if (!dir.exists(folder_path)) dir.create(folder_path, recursive = TRUE)
folder_path_1stfolder <- folder_path

shared_out_dir <- here("Results", "Figures")
if (!dir.exists(shared_out_dir)) dir.create(shared_out_dir, recursive = TRUE)

# ============================================================================
# INPUT FILES
# ============================================================================
# Proliferation scores (generated by Tissue_proliferation_index.R)
csv_prolif_of_tissues <- here("Data", "gtex", "Processed", "proliferation_index_Jack_Devine_namesChanged.csv")

if (!file.exists(csv_prolif_of_tissues)) {
  stop(paste0(
    "\n============================================================\n",
    "ERROR: Proliferation index file not found!\n\n",
    "Expected: ", csv_prolif_of_tissues, "\n\n",
    "Please run Scripts/gtex/Tissue_proliferation_index.R first.\n",
    "============================================================\n"
  ))
}
proliferation_scores <- read.csv(csv_prolif_of_tissues)

# NOTE: proliferation_score is log2-scaled from Tissue_proliferation_index.R
# (method: sum(3 raw TPMs) per sample → average raw sums across donors → log2)
# No further log2 transformation needed.

# ISR scores: build per-tissue Avg_Factor1 from per-tissue Plot_Data CSVs
# (replaces the legacy Averages_of_ISR_and_GDF15.csv, which was never written
# by any script in this repo). Filter to Hospital inpatient + Emergency room
# to match the deathplace-only averages the downstream merge expects.
source(here("Main Figure Scripts", "Helper Scripts",
            "Load_All_Tissue_DTHPLCE.R"))
all_donor_data <- load_all_tissue_dthplce() %>%
  filter(DTHPLCE %in% c("Hospital inpatient", "Emergency room"))

ISR_scores <- all_donor_data %>%
  filter(fa_vs_gdf15 == "Factor1") %>%
  group_by(Tissue) %>%
  summarise(
    Avg_Factor1 = mean(value, na.rm = TRUE),
    SD_Factor1  = sd(value,   na.rm = TRUE),
    SEM_Factor1 = SD_Factor1 / sqrt(sum(!is.na(value))),
    N_Factor1   = sum(!is.na(value)),
    .groups = "drop"
  )

# Significance results (Hedges G) — written by Figure_4C.R
csv_sig <- here("Results", "Figures", "Figure_4C", "1_Hedges_G_results.csv")
if (!file.exists(csv_sig)) {
  stop(paste0(
    "\n============================================================\n",
    "ERROR: Hedges G results not found at:\n  ", csv_sig, "\n\n",
    "Please run Figure_4C.R before Figure 4E.\n",
    "============================================================\n"
  ))
}
sig_columns <- read.csv(csv_sig)

# ============================================================================
# MERGE DATA
# ============================================================================
# Debug: Show tissue names to check for mismatches
message("\n=== Checking tissue name matching ===")
message("Tissues in ISR_scores: ", nrow(ISR_scores))
message("Tissues in proliferation_scores: ", nrow(proliferation_scores))

# Perform a left join to add the proliferation_score column to ISR_score
merged_df <- merge(ISR_scores, proliferation_scores[, c("Tissue", "proliferation_score")],
                   by = "Tissue",
                   all.x = TRUE)

# Show which tissues are missing proliferation scores
missing_prolif <- merged_df %>% filter(is.na(proliferation_score)) %>% pull(Tissue)
if (length(missing_prolif) > 0) {
  message("\nWARNING: ", length(missing_prolif), " tissues missing proliferation scores:")
  message(paste("  -", missing_prolif, collapse = "\n"))
  message("\nThese tissue names in proliferation_scores:")
  message(paste(head(proliferation_scores$Tissue, 10), collapse = ", "), "...")
}

# Split into Factor1_sig and GDF15_sig
Factor1_sig <- sig_columns %>%
  filter(Comparison == "Hospital inpatient_Factor1 vs Emergency room_Factor1") %>%
  distinct(Tissue, .keep_all = TRUE)

GDF15_sig <- sig_columns %>%
  filter(Comparison == "Hospital inpatient_GDF15 vs Emergency room_GDF15") %>%
  distinct(Tissue, .keep_all = TRUE)

# Add the Significant column from Factor1_sig to merged_df
merged_df <- merged_df %>%
  left_join(Factor1_sig %>% select(Tissue, Significant), by = "Tissue")

merged_df <- merged_df %>%
  left_join(Factor1_sig %>% select(Tissue, Cohens_D), by = "Tissue") %>%
  mutate(deathplace_comparison = ifelse(Cohens_D > 0, "HI>ER", "ER>HI"))

# Drop the Cohens_D column if not needed
merged_df <- merged_df %>% select(-Cohens_D)


# Define tissues to remove
tissues_to_remove <- c("pancreas", "kidney_cortex", "uterus", "vagina", "spleen", "small_intestines_terminal_ileum")

# Filter out the unwanted tissues
filtered_df <- merged_df %>%
  filter(!Tissue %in% tissues_to_remove)

merged_df <- filtered_df

# ============================================================================
# PREPARE DATA FOR FIGURE 4E
# ============================================================================
# Here we are Filtering by Significance= Significant:

data <- merged_df %>%
  select(Tissue, Avg_Factor1, proliferation_score, Significant, deathplace_comparison)

data_sig <- data %>%
  filter(Significant != "Not Significant")

# Calculate the median of the proliferation_score column (needed for grouping)
median_proliferation_score <- median(data_sig$proliferation_score, na.rm = TRUE)

# Add Proliferative_Group for complete data_sig
data_sig <- data_sig %>%
  mutate(Proliferative_Group = ifelse(proliferation_score > median_proliferation_score, "Proliferative", "Non-Proliferative"))

#####
# 2 #  THIS IS FIGURE 4E
#####

# Check normality for proliferation_score in both deathplace groups
normality_results2 <- data_sig %>%
  group_by(deathplace_comparison) %>%
  summarise(shapiro_p_value = shapiro.test(proliferation_score)$p.value)

print(normality_results2)

  # Perform Wilcoxon rank-sum test
test_result2 <- wilcox.test(proliferation_score ~ deathplace_comparison, data = data_sig)


# View test result
print(test_result2)


# Filter data for HI>ER and ER>HI groups AND remove NA proliferation scores
subset_data2 <- data_sig %>%
  filter(deathplace_comparison %in% c("HI>ER", "ER>HI")) %>%
  filter(!is.na(proliferation_score))

# Print sample sizes
message("\n=== Sample Sizes (after removing NA proliferation scores) ===")
message("ER>HI: ", sum(subset_data2$deathplace_comparison == "ER>HI"))
message("HI>ER: ", sum(subset_data2$deathplace_comparison == "HI>ER"))
message("Total: ", nrow(subset_data2))

# # Calculate Cohen's d with Hedges' g correction
# BUG FIX: Was using subset_data instead of subset_data2
hedges_g2 <- cohen.d(subset_data2$proliferation_score,
                    as.factor(subset_data2$deathplace_comparison),
                    hedges.correction = TRUE)

g2_value <- hedges_g2$estimate

# Print the result
print(g2_value)

# View the result
print(hedges_g2)


# Define custom colors — matching the Prism plot style (pink/magenta and gold/orange)
custom_colors <- c("ER>HI" = "#C44E8B", "HI>ER" = "#E8A735")

# Helper: median ± SEM (SEM calculated as SD / sqrt(n))
median_se_lower <- function(x) median(x, na.rm = TRUE) - sd(x, na.rm = TRUE) / sqrt(sum(!is.na(x)))
median_se_upper <- function(x) median(x, na.rm = TRUE) + sd(x, na.rm = TRUE) / sqrt(sum(!is.na(x)))

# Compute y-axis limits from data with 10% padding
y_range_4E <- range(data_sig$proliferation_score, na.rm = TRUE)
y_pad_4E   <- diff(y_range_4E) * 0.1
y_lim_4E   <- c(y_range_4E[1] - y_pad_4E, y_range_4E[2] + y_pad_4E)

# Create the plot (FIGURE 4E) — Prism-style with individual points + median ± SEM
plot_4E <- ggplot(data_sig, aes(x = deathplace_comparison, y = proliferation_score, color = deathplace_comparison)) +
  # Individual tissue data points
  geom_jitter(width = 0.15, size = 4, alpha = 0.8) +
  # Median crossbar
  stat_summary(fun = median, geom = "crossbar", width = 0.3,
               aes(ymin = after_stat(y), ymax = after_stat(y)),
               linewidth = 0.7) +
  # SEM error bars centered on median
  stat_summary(fun = median, fun.min = median_se_lower, fun.max = median_se_upper,
               geom = "errorbar", width = 0.15, linewidth = 0.7) +
  scale_color_manual(values = custom_colors) +
  scale_y_continuous(limits = y_lim_4E, expand = c(0, 0)) +
  scale_x_discrete(expand = expansion(add = 0.6)) +
  labs(
    x = NULL,
    y = "Proliferation Score (log2)"
  ) +
  theme_classic(base_size = 16) +
  theme(
    legend.position = "none",
    axis.text = element_text(color = "black", size = 14),
    axis.title = element_text(color = "black", size = 16),
    axis.line = element_line(color = "black"),
    axis.ticks = element_line(color = "black")
  )

# Display the plot
print(plot_4E)

ggsave(filename = file.path(folder_path_1stfolder, paste0("prolifScore_per_dthplce_comparison_Hedges_G_", round(g2_value, 3), ".png")), plot = plot_4E, width = 6, height = 7, dpi = 300)

# Save as Figure_4E.png to shared output folder
ggsave(filename = file.path(shared_out_dir, "Figure_4E.png"), plot = plot_4E, width = 6, height = 7, dpi = 300)

message("\n=== Figure 4E Complete ===")
message("Hedges G (proliferation by death place): ", round(g2_value, 3))
message("ER>HI tissues: ", sum(subset_data2$deathplace_comparison == "ER>HI"))
message("HI>ER tissues: ", sum(subset_data2$deathplace_comparison == "HI>ER"))
message("Saved to: ", file.path(shared_out_dir, "Figure_4E.png"))

# ============================================================================
# SAVE SOURCE DATA FOR FIGURE 4E
# ============================================================================
message("\nExporting source data for Figure 4E...")

# Prepare source data for the main figure (proliferation scores by death place comparison)
# Include only the columns shown in the plot
source_data <- data_sig %>%
  select(Tissue, deathplace_comparison, proliferation_score)

# Save to CSV
csv_source_file <- file.path(folder_path, "Figure_4E_source_data.csv")
write.csv(source_data, csv_source_file, row.names = FALSE)

message("  Saved: Figure_4E_source_data.csv")
message("  Location: ", folder_path)
